### ISSUE TITLE
Nonetype error on reading 32FP wav data in proc_audio.py

### ISSUE THREAD

**Issue by GuitarML** [Alec-Wright/CoreAudioML#4]
@Alec-Wright I tried using my own mono/32FP wav data with proc_audio.py but got a Nonetype error, I think you just need to modify the "audio_converter" function to return data for either case.

```
# Function converting np read audio to range of -1 to +1
def audio_converter(audio):
    if audio.dtype == 'int16':
        return audio.astype(np.float32, order='C') / 32768.0
    else:
        print('unimplemented audio data type conversion...')
        return audio.astype(np.float32, order='C')   ########   < ---------- My added line
```

When I just used ```return audio```, I got a Numpy warning, but it still worked.

After that the prediction worked great for me, I'm planning on trying to train my own model next. Thanks!

**Comment by JamesJieranShen** [comment]
Hello, was just working on this project and encountered the same issue. I believe this fix improves the robustness of the error message:
```
def audio_converter(audio):
    if audio.dtype == 'float32':
        return audio.astype(np.float32, order='C')
    if audio.dtype == 'int16':
        return audio.astype(np.float32, order='C') / 32768.0
    else:
        assert True, 'unimplemented audio data type conversion...'
```
